# Generated by Django 5.2.3 on 2025-07-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdetail",
            name="assigned_to",
        ),
    ]
