# Generated by Django 5.2.3 on 2025-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_taskdetail_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default="L",
                max_length=1,
            ),
        ),
    ]
