# Generated by Django 5.2.3 on 2025-07-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_taskdetail_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
    ]
