# Generated by Django 5.2.3 on 2025-07-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_remove_task_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
    ]
