# Generated by Django 5.2.3 on 2025-07-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_task_assigned_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
