# Generated by Django 5.2.3 on 2025-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_delete_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="tasks_asset"),
        ),
    ]
